plugins {
    id 'java-library'
    id 'maven-publish'
}

group = 'org.writer'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
    withSourcesJar()
    withJavadocJar()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

dependencies {
    compileOnly libs.lombok
    annotationProcessor libs.lombok

    implementation libs.javafaker

    testImplementation libs.junit.jupiter
    testImplementation libs.assertj.core
}

test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
    }
}
